# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Lottery.ui'
#
# Created: Sun Aug 11 16:09:06 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(482, 318)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.blueNumber = QtGui.QLCDNumber(self.centralwidget)
        self.blueNumber.setGeometry(QtCore.QRect(310, 220, 41, 51))
        self.blueNumber.setDigitCount(2)
        self.blueNumber.setProperty("intValue", 88)
        self.blueNumber.setObjectName(_fromUtf8("blueNumber"))
        self.hopeButton = QtGui.QPushButton(self.centralwidget)
        self.hopeButton.setGeometry(QtCore.QRect(380, 230, 61, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.hopeButton.setFont(font)
        self.hopeButton.setObjectName(_fromUtf8("hopeButton"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 10, 171, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(40, 230, 251, 41))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.splitter_2 = QtGui.QSplitter(self.splitter)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.redNumber_1 = QtGui.QLCDNumber(self.splitter_2)
        self.redNumber_1.setDigitCount(2)
        self.redNumber_1.setProperty("intValue", 88)
        self.redNumber_1.setObjectName(_fromUtf8("redNumber_1"))
        self.redNumber_2 = QtGui.QLCDNumber(self.splitter_2)
        self.redNumber_2.setDigitCount(2)
        self.redNumber_2.setProperty("intValue", 88)
        self.redNumber_2.setObjectName(_fromUtf8("redNumber_2"))
        self.redNumber_3 = QtGui.QLCDNumber(self.splitter_2)
        self.redNumber_3.setDigitCount(2)
        self.redNumber_3.setProperty("intValue", 88)
        self.redNumber_3.setObjectName(_fromUtf8("redNumber_3"))
        self.redNumber_4 = QtGui.QLCDNumber(self.splitter_2)
        self.redNumber_4.setDigitCount(2)
        self.redNumber_4.setProperty("intValue", 88)
        self.redNumber_4.setObjectName(_fromUtf8("redNumber_4"))
        self.redNumber_5 = QtGui.QLCDNumber(self.splitter_2)
        self.redNumber_5.setDigitCount(2)
        self.redNumber_5.setProperty("intValue", 88)
        self.redNumber_5.setObjectName(_fromUtf8("redNumber_5"))
        self.redNumber_6 = QtGui.QLCDNumber(self.splitter_2)
        self.redNumber_6.setDigitCount(2)
        self.redNumber_6.setProperty("intValue", 88)
        self.redNumber_6.setObjectName(_fromUtf8("redNumber_6"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(240, 50, 231, 151))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.fliterBox_6 = QtGui.QCheckBox(self.widget)
        self.fliterBox_6.setObjectName(_fromUtf8("fliterBox_6"))
        self.verticalLayout.addWidget(self.fliterBox_6)
        self.fliterBox_7 = QtGui.QCheckBox(self.widget)
        self.fliterBox_7.setObjectName(_fromUtf8("fliterBox_7"))
        self.verticalLayout.addWidget(self.fliterBox_7)
        self.fliterBox_8 = QtGui.QCheckBox(self.widget)
        self.fliterBox_8.setObjectName(_fromUtf8("fliterBox_8"))
        self.verticalLayout.addWidget(self.fliterBox_8)
        self.fliterBox_9 = QtGui.QCheckBox(self.widget)
        self.fliterBox_9.setObjectName(_fromUtf8("fliterBox_9"))
        self.verticalLayout.addWidget(self.fliterBox_9)
        self.fliterBox_10 = QtGui.QCheckBox(self.widget)
        self.fliterBox_10.setObjectName(_fromUtf8("fliterBox_10"))
        self.verticalLayout.addWidget(self.fliterBox_10)
        self.widget1 = QtGui.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(20, 50, 201, 151))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.fliterBox_1 = QtGui.QCheckBox(self.widget1)
        self.fliterBox_1.setChecked(True)
        self.fliterBox_1.setObjectName(_fromUtf8("fliterBox_1"))
        self.verticalLayout_2.addWidget(self.fliterBox_1)
        self.fliterBox_2 = QtGui.QCheckBox(self.widget1)
        self.fliterBox_2.setObjectName(_fromUtf8("fliterBox_2"))
        self.verticalLayout_2.addWidget(self.fliterBox_2)
        self.fliterBox_3 = QtGui.QCheckBox(self.widget1)
        self.fliterBox_3.setObjectName(_fromUtf8("fliterBox_3"))
        self.verticalLayout_2.addWidget(self.fliterBox_3)
        self.fliterBox_4 = QtGui.QCheckBox(self.widget1)
        self.fliterBox_4.setObjectName(_fromUtf8("fliterBox_4"))
        self.verticalLayout_2.addWidget(self.fliterBox_4)
        self.fliterBox_5 = QtGui.QCheckBox(self.widget1)
        self.fliterBox_5.setObjectName(_fromUtf8("fliterBox_5"))
        self.verticalLayout_2.addWidget(self.fliterBox_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 482, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Lottery", None))
        self.hopeButton.setText(_translate("MainWindow", "机选", None))
        self.label.setText(_translate("MainWindow", "彩票选号器", None))
        self.fliterBox_6.setText(_translate("MainWindow", "过滤器1", None))
        self.fliterBox_7.setText(_translate("MainWindow", "过滤器1", None))
        self.fliterBox_8.setText(_translate("MainWindow", "过滤器1", None))
        self.fliterBox_9.setText(_translate("MainWindow", "过滤器1", None))
        self.fliterBox_10.setText(_translate("MainWindow", "过滤器1", None))
        self.fliterBox_1.setText(_translate("MainWindow", "过滤器1", None))
        self.fliterBox_2.setText(_translate("MainWindow", "过滤器1", None))
        self.fliterBox_3.setText(_translate("MainWindow", "过滤器1", None))
        self.fliterBox_4.setText(_translate("MainWindow", "过滤器1", None))
        self.fliterBox_5.setText(_translate("MainWindow", "过滤器1", None))

